os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor -v
jobs:
  include:
    - stage: Test
    script: ./flutter/bin/flutter test --machine
cache:
  directories:
    - $HOME/.pub-cache