version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - codecov/upload:
          file: {{ coverage }}
          token: 9350fc27-28b7-44b0-a2bb-623054fb62cf
      - run: flutter doctor
      - run: flutter test --coverage