version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - codecov/upload:
          file: {{ coverage }}
      - run: flutter doctor
      - run: flutter test --coverage